/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FINAL = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int PRINT = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int FUNC = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int KLAMMERAUF = 16;
  /** RegularExpression Id. */
  int KLAMMERZU = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MAL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int ComOp = 22;
  /** RegularExpression Id. */
  int IDENT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"final\"",
    "\"int\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"void\"",
    "\"func\"",
    "\"return\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<ComOp>",
    "<IDENT>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
  };

}
